Examples update
2bttns/2bttns pull request #46
Opened 2023-08-10 00:33 UTC by mriziq

Added express JS example and renamed Next example

2023-08-10 00:42 UTC, DOORM4T approved these changes

2023-08-10 00:45 UTC, DOORM4T requested changes
The express example needs a .gitignore for node_modules

It could also use default seed IDs like example-game-0 for the game to make setup more convenient.

2023-08-11 05:17 UTC, mriziq commented
Ready for your review

2023-08-11 06:05 UTC, DOORM4T approved these changes

2023-08-11 06:06 UTC, merged